# Generated by Django 2.0.6 on 2018-08-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180820_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category', verbose_name='Category'),
        ),
    ]
